services:
  downloader-server:
    build:
      context: .
      dockerfile: downloader-server/Dockerfile.dev
    ports:
      - "3031:3031"
    volumes:
      - .:/workspace
    working_dir: /workspace/downloader-server
    command: go run .

  web-frontend:
    build:
      context: ./web-app/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "3034:3034"
    volumes:
      - ./web-app/frontend:/web-app/frontend
      - /web-app/frontend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - web-backend
    working_dir: /web-app/frontend

  web-backend:
    build:
      context: .
      dockerfile: web-app/backend/Dockerfile.dev
    ports:
      - "3033:3033"
    volumes:
      - ./web-app/backend:/web-app/backend
    working_dir: /web-app/web-app/backend
    command: go run .

  message-queue:
    build:
      context: .
      dockerfile: message-queue/Dockerfile.dev
    ports:
      - "3032:3032"
    volumes:
      - .:/workspace
    working_dir: /workspace/message-queue
    depends_on:
      - downloader-server
    command: go run .
